### ISSUE TITLE
Sprint 1 User Story 11: transaction records

### ISSUE THREAD

**Issue by nickysemenza** [CryptoCardsETH/cryptocards#11]
- [x] Setup a basic “Buy” button on cards to add them to your account (#25)
- [x] Keep a record of all card exchanges as transactions
- [x] View transaction history for each account

**Comment by daywhirls** [comment]
Recording transaction history is complete. User story finished,

**Comment by harrischristiansen** [comment]
https://github.com/CryptoCardsETH/cryptocards/pull/25
