### ISSUE TITLE
Sprint 1 User Story 12: sorting cards

### ISSUE THREAD

**Issue by nickysemenza** [CryptoCardsETH/cryptocards#12]
- [x] Sort cards alphabetically
- [ ] Sort cards by popularity
- [ ] Sort cards by price
- [ ] Sort cards by attributes

**Comment by nickysemenza** [comment]
how do we determine popularity, and how do we sort by attributes?

**Comment by harrischristiansen** [comment]
For popularity lets currently sort by number of battles. We can replace this with another sorting method once there are methods for following players/cards.

For sorting by attributes, lets have like-kind attributes grouped together and then sorted by int value. For instance, all cards with attribute `mechanical` will be grouped together.
