### ISSUE TITLE
Sprint 2 User Story 5: On-demand card generation

### ISSUE THREAD

**Issue by nickysemenza** [CryptoCardsETH/cryptocards#50]
- [ ] Allow an admin to generate generation-0 and promo cards on-demand by sending a transaction to our contract
- [ ] Create a contract for distributing battle rewards, and send the reward

**Comment by harrischristiansen** [comment]
Admin's can create gen-0 cards by calling `function createGen0Card() external returns (uint256 newCardID)`
#102 

Battle rewards are distributed by `function rewardWinner(uint256 _winnerGroup) private returns (uint256 cardID)`
#112
