### ISSUE TITLE
Sprint 2 User Story 8: Admin reporting

### ISSUE THREAD

**Issue by nickysemenza** [CryptoCardsETH/cryptocards#53]
- [x] Create a current players report for admins, with stats such as cardCount, battleCount, win%, etc.
- [ ] Create a transactions report with stats about all transactions, including seller, buyer, card, and price.
- [ ] Create a transactions list on the card detail page for displaying all transactions involving that card
- [ ] Create a transactions report with stats about token creation, including graphs of tokens created over time (maybe use https://www.amcharts.com)

**Comment by nickysemenza** [comment]
@bbemis017 checkout http://recharts.org

**Comment by bbemis017** [comment]
@harrischristiansen @Shonas301 Just to make sure I'm on the same page. I should query this data from mysql and the solidity code will fire an event that our backend will pick up and update the mysql database.

**Comment by nickysemenza** [comment]
@bbemis017 all the data on transactions, users, etc should already be cached in the DB technically, since it'll be persisted to the DB as soon as each disparate transaction is put on the blockchain. 
SO i don't think we'd need to interact with solidity for this, since it's only reading that's happening (except for say blacklisting users/cards, but that's #57, but does live under the admin section)

We could run into into a situation where for some reason the backend doesn't pickup on some blockchain txn happening, so perhaps we should do some sort of periodic DB state reconciliation on a cronjob. (although how does gas work for that if we are querying the blockchain un-prompted??)

**Comment by bbemis017** [comment]
ok cool, I just wanted to double check before I starting building it.

As far as doing some kind of syncing operation, it should probably be avoided. But I think crypto kitties does something like that every once in a while.
