### ISSUE TITLE
 Sprint 3 User Story 8: higher txn fee for faster txns

### ISSUE THREAD

**Issue by nickysemenza** [CryptoCardsETH/cryptocards#88]
As a user, I would like the ability to pay a higher transaction fee for a faster battle transaction

- [ ] Allow the user to specify gas amount. Higher gas amounts will ensure the transaction is processed quickly by the Ethereum network.
- [ ] Test functionality

**Comment by harrischristiansen** [comment]
This can be achieved by setting a higher gas value in MetaMask.
